export interface Festival {
  id: string
  name: string
  dates: string
  location: string
  price: string
  priceValue: number
  capacity: string
  musicTypes: string[]
  atmosphere: string[]
  description: string
  ticketLink: string
  image: string
  featured: boolean
  camping: boolean
  familyFriendly: boolean
  weather: {
    avgTemp: string
    rainChance: string
  }
}

export const festivals: Festival[] = [
  {
    id: "glastonbury",
    name: "Glastonbury Festival",
    dates: "24-28 June 2026",
    location: "Pilton, Somerset",
    price: "£355 + £5 booking fee",
    priceValue: 360,
    capacity: "210,000",
    musicTypes: ["Rock", "Pop", "Electronic", "World", "Indie", "Hip-Hop"],
    atmosphere: ["Legendary", "Diverse", "Artistic", "Muddy"],
    description:
      "The world's most famous performing arts festival. Five days of music, theatre, circus, cabaret and more across 900 acres.",
    ticketLink: "https://glastonburyfestivals.co.uk",
    image: "/glastonbury-festival-main-stage-crowd.jpg",
    featured: true,
    camping: true,
    familyFriendly: true,
    weather: { avgTemp: "18°C", rainChance: "45%" },
  },
  {
    id: "reading-leeds",
    name: "Reading & Leeds Festival",
    dates: "28-30 August 2026",
    location: "Reading / Leeds",
    price: "£275",
    priceValue: 275,
    capacity: "90,000 each",
    musicTypes: ["Rock", "Alternative", "Punk", "Metal", "Indie"],
    atmosphere: ["Energetic", "Young", "Rowdy", "Intense"],
    description: "The UK's biggest dual-site festival celebrating rock, alternative, and indie music since 1961.",
    ticketLink: "https://www.readingfestival.com",
    image: "/reading-festival-rock-concert-stage-fire.jpg",
    featured: true,
    camping: true,
    familyFriendly: false,
    weather: { avgTemp: "19°C", rainChance: "35%" },
  },
  {
    id: "creamfields",
    name: "Creamfields",
    dates: "27-30 August 2026",
    location: "Daresbury, Cheshire",
    price: "£245",
    priceValue: 245,
    capacity: "70,000",
    musicTypes: ["EDM", "House", "Techno", "Trance", "Drum & Bass"],
    atmosphere: ["High-Energy", "Rave", "Neon", "24-Hour"],
    description: "The UK's biggest dance music festival featuring the world's best DJs across multiple stages.",
    ticketLink: "https://www.creamfields.com",
    image: "/creamfields-electronic-dance-music-festival-lasers.jpg",
    featured: true,
    camping: true,
    familyFriendly: false,
    weather: { avgTemp: "18°C", rainChance: "40%" },
  },
  {
    id: "download",
    name: "Download Festival",
    dates: "12-14 June 2026",
    location: "Donington Park, Leicestershire",
    price: "£285",
    priceValue: 285,
    capacity: "111,000",
    musicTypes: ["Metal", "Rock", "Punk", "Hard Rock"],
    atmosphere: ["Heavy", "Brotherhood", "Intense", "Legendary"],
    description: "The spiritual home of rock and metal. Three days of the heaviest music on the planet.",
    ticketLink: "https://downloadfestival.co.uk",
    image: "/download-festival-metal-concert-pyrotechnics.jpg",
    featured: true,
    camping: true,
    familyFriendly: false,
    weather: { avgTemp: "17°C", rainChance: "35%" },
  },
  {
    id: "isle-of-wight",
    name: "Isle of Wight Festival",
    dates: "18-21 June 2026",
    location: "Newport, Isle of Wight",
    price: "£235",
    priceValue: 235,
    capacity: "55,000",
    musicTypes: ["Rock", "Pop", "Indie", "Classic Rock"],
    atmosphere: ["Relaxed", "Family", "Scenic", "Classic"],
    description: "Historic festival in a beautiful island setting. Great mix of legendary and contemporary acts.",
    ticketLink: "https://isleofwightfestival.com",
    image: "/isle-of-wight-festival-crowd-seaside.jpg",
    featured: false,
    camping: true,
    familyFriendly: true,
    weather: { avgTemp: "19°C", rainChance: "25%" },
  },
  {
    id: "parklife",
    name: "Parklife Festival",
    dates: "13-14 June 2026",
    location: "Heaton Park, Manchester",
    price: "£155",
    priceValue: 155,
    capacity: "80,000",
    musicTypes: ["Hip-Hop", "Grime", "Electronic", "Indie", "R&B"],
    atmosphere: ["Urban", "Trendy", "Youthful", "Vibrant"],
    description: "Manchester's biggest inner-city festival celebrating urban music, electronic beats, and indie vibes.",
    ticketLink: "https://parklife.uk.com",
    image: "/parklife-festival-manchester-urban-music-crowd.jpg",
    featured: false,
    camping: false,
    familyFriendly: false,
    weather: { avgTemp: "18°C", rainChance: "40%" },
  },
  {
    id: "wireless",
    name: "Wireless Festival",
    dates: "10-12 July 2026",
    location: "Finsbury Park, London",
    price: "£175",
    priceValue: 175,
    capacity: "50,000",
    musicTypes: ["Hip-Hop", "R&B", "Grime", "Rap", "Afrobeats"],
    atmosphere: ["Urban", "Hype", "London", "Star-Studded"],
    description: "London's premier urban music festival featuring the biggest names in hip-hop, R&B, and grime.",
    ticketLink: "https://wirelessfestival.co.uk",
    image: "/wireless-festival-london-hip-hop-crowd.jpg",
    featured: false,
    camping: false,
    familyFriendly: false,
    weather: { avgTemp: "21°C", rainChance: "25%" },
  },
  {
    id: "bst-hyde-park",
    name: "BST Hyde Park",
    dates: "3-12 July 2026",
    location: "Hyde Park, London",
    price: "£85-175",
    priceValue: 130,
    capacity: "65,000",
    musicTypes: ["Pop", "Rock", "R&B", "Indie"],
    atmosphere: ["Premium", "Relaxed", "Central London", "Diverse"],
    description: "Single-day events featuring global superstars in the heart of London's iconic Hyde Park.",
    ticketLink: "https://www.bst-hydepark.com",
    image: "/bst-hyde-park-concert-london-sunset.jpg",
    featured: false,
    camping: false,
    familyFriendly: true,
    weather: { avgTemp: "22°C", rainChance: "20%" },
  },
  {
    id: "latitude",
    name: "Latitude Festival",
    dates: "16-19 July 2026",
    location: "Henham Park, Suffolk",
    price: "£270",
    priceValue: 270,
    capacity: "40,000",
    musicTypes: ["Indie", "Alternative", "Folk", "Jazz", "Electronic"],
    atmosphere: ["Cultured", "Relaxed", "Artsy", "Family"],
    description: "Arts and music festival in beautiful Suffolk parkland. Music, theatre, dance, poetry, comedy.",
    ticketLink: "https://www.latitudefestival.com",
    image: "/latitude-festival-suffolk-colorful-art-music.jpg",
    featured: false,
    camping: true,
    familyFriendly: true,
    weather: { avgTemp: "20°C", rainChance: "30%" },
  },
  {
    id: "tramlines",
    name: "Tramlines Festival",
    dates: "24-26 July 2026",
    location: "Hillsborough Park, Sheffield",
    price: "£140",
    priceValue: 140,
    capacity: "40,000",
    musicTypes: ["Indie", "Rock", "Pop", "Dance"],
    atmosphere: ["Friendly", "Local", "Affordable", "Welcoming"],
    description: "Sheffield's biggest music festival with an amazing lineup and legendary friendly atmosphere.",
    ticketLink: "https://tramlines.org.uk",
    image: "/tramlines-festival-sheffield-indie-music-crowd.jpg",
    featured: false,
    camping: false,
    familyFriendly: true,
    weather: { avgTemp: "19°C", rainChance: "35%" },
  },
  {
    id: "kendal-calling",
    name: "Kendal Calling",
    dates: "30 July - 2 August 2026",
    location: "Lowther Deer Park, Lake District",
    price: "£210",
    priceValue: 210,
    capacity: "25,000",
    musicTypes: ["Indie", "Rock", "Electronic", "Folk"],
    atmosphere: ["Scenic", "Intimate", "Fancy Dress", "Community"],
    description: "Award-winning Lake District festival known for fancy dress themes and incredible scenery.",
    ticketLink: "https://www.kendalcalling.co.uk",
    image: "/kendal-calling-lake-district-festival-mountains.jpg",
    featured: false,
    camping: true,
    familyFriendly: true,
    weather: { avgTemp: "17°C", rainChance: "50%" },
  },
  {
    id: "bestival",
    name: "Camp Bestival",
    dates: "30 July - 2 August 2026",
    location: "Lulworth Castle, Dorset",
    price: "£260",
    priceValue: 260,
    capacity: "30,000",
    musicTypes: ["Pop", "Indie", "Electronic", "Family"],
    atmosphere: ["Family", "Colourful", "Magical", "Theatrical"],
    description: "The ultimate family festival with world-class music, entertainment, and activities for all ages.",
    ticketLink: "https://campbestival.net",
    image: "/camp-bestival-colorful-family-festival-castle.jpg",
    featured: false,
    camping: true,
    familyFriendly: true,
    weather: { avgTemp: "20°C", rainChance: "30%" },
  },
  {
    id: "womad",
    name: "WOMAD",
    dates: "23-26 July 2026",
    location: "Charlton Park, Wiltshire",
    price: "£225",
    priceValue: 225,
    capacity: "35,000",
    musicTypes: ["World", "Folk", "Reggae", "African", "Latin"],
    atmosphere: ["Global", "Cultural", "Peaceful", "Educational"],
    description: "World of Music, Arts and Dance. Celebrating global sounds and cultures for over 40 years.",
    ticketLink: "https://womad.co.uk",
    image: "/womad-world-music-festival-cultural-drums.jpg",
    featured: false,
    camping: true,
    familyFriendly: true,
    weather: { avgTemp: "20°C", rainChance: "30%" },
  },
  {
    id: "all-points-east",
    name: "All Points East",
    dates: "22-31 August 2026",
    location: "Victoria Park, London",
    price: "£75-95",
    priceValue: 85,
    capacity: "40,000",
    musicTypes: ["Indie", "Rock", "Pop", "Electronic"],
    atmosphere: ["Urban", "Relaxed", "East London", "Foodie"],
    description: "East London's premier festival with headline acts and incredible street food in Victoria Park.",
    ticketLink: "https://www.allpointseastfestival.com",
    image: "/all-points-east-victoria-park-london-music.jpg",
    featured: false,
    camping: false,
    familyFriendly: true,
    weather: { avgTemp: "19°C", rainChance: "25%" },
  },
  {
    id: "we-are-fstvl",
    name: "We Are FSTVL",
    dates: "23-24 May 2026",
    location: "Damyns Hall, Essex",
    price: "£130",
    priceValue: 130,
    capacity: "40,000",
    musicTypes: ["House", "Techno", "Garage", "Bass"],
    atmosphere: ["Rave", "Underground", "Hedonistic", "24-Hour"],
    description: "Essex's biggest dance music festival featuring house, techno, and everything in between.",
    ticketLink: "https://wearefstvl.com",
    image: "/we-are-fstvl-dance-music-festival-rave.jpg",
    featured: false,
    camping: true,
    familyFriendly: false,
    weather: { avgTemp: "16°C", rainChance: "30%" },
  },
  {
    id: "green-man",
    name: "Green Man Festival",
    dates: "20-23 August 2026",
    location: "Brecon Beacons, Wales",
    price: "£230",
    priceValue: 230,
    capacity: "25,000",
    musicTypes: ["Indie", "Folk", "Alternative", "Psychedelic"],
    atmosphere: ["Mystical", "Green", "Independent", "Beautiful"],
    description: "Independent arts and music festival in the stunning Brecon Beacons. Known for the Green Man burning.",
    ticketLink: "https://www.greenman.net",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    camping: true,
    familyFriendly: true,
    weather: { avgTemp: "17°C", rainChance: "45%" },
  },
]

export const packingCategories = [
  {
    name: "Essentials",
    icon: "tent",
    items: [
      { name: "Tent (waterproof!)", essential: true },
      { name: "Sleeping bag", essential: true },
      { name: "Sleeping mat/air mattress", essential: true },
      { name: "Pillow", essential: false },
      { name: "Festival ticket", essential: true },
      { name: "ID (passport/driving licence)", essential: true },
      { name: "Cash (ATMs often have long queues)", essential: true },
      { name: "Bank cards", essential: true },
      { name: "Phone & charger", essential: true },
      { name: "Portable power bank", essential: true },
    ],
  },
  {
    name: "Clothing",
    icon: "shirt",
    items: [
      { name: "Wellies/waterproof boots", essential: true },
      { name: "Waterproof jacket", essential: true },
      { name: "Warm hoodie/fleece", essential: true },
      { name: "Shorts", essential: false },
      { name: "T-shirts (x5)", essential: false },
      { name: "Underwear & socks", essential: true },
      { name: "Sunglasses", essential: false },
      { name: "Hat (sun/rain)", essential: false },
      { name: "Comfortable trainers", essential: false },
      { name: "Pyjamas", essential: false },
    ],
  },
  {
    name: "Toiletries",
    icon: "sparkles",
    items: [
      { name: "Toilet roll (LOTS)", essential: true },
      { name: "Wet wipes", essential: true },
      { name: "Hand sanitiser", essential: true },
      { name: "Toothbrush & toothpaste", essential: true },
      { name: "Deodorant", essential: true },
      { name: "Dry shampoo", essential: false },
      { name: "Sunscreen SPF30+", essential: true },
      { name: "Medications", essential: true },
      { name: "First aid kit", essential: false },
      { name: "Feminine hygiene products", essential: false },
    ],
  },
  {
    name: "Camping Extras",
    icon: "flashlight",
    items: [
      { name: "Torch/headlamp", essential: true },
      { name: "Camping chair", essential: false },
      { name: "Cool box", essential: false },
      { name: "Reusable water bottle", essential: true },
      { name: "Bin bags", essential: true },
      { name: "Gaffer tape", essential: false },
      { name: "Mallet for tent pegs", essential: false },
      { name: "Ear plugs", essential: true },
      { name: "Eye mask", essential: false },
      { name: "Flag/marker for your tent", essential: true },
    ],
  },
  {
    name: "Food & Drink",
    icon: "utensils",
    items: [
      { name: "Snacks (cereal bars, crisps)", essential: false },
      { name: "Breakfast items", essential: false },
      { name: "Tea/coffee supplies", essential: false },
      { name: "Portable stove (check festival rules)", essential: false },
      { name: "Cups/plates/cutlery", essential: false },
      { name: "Can opener", essential: false },
      { name: "Water purification tablets", essential: false },
    ],
  },
  {
    name: "Fun Extras",
    icon: "party-popper",
    items: [
      { name: "Fancy dress outfit", essential: false },
      { name: "Glitter & face paint", essential: false },
      { name: "Camera", essential: false },
      { name: "Bluetooth speaker (small)", essential: false },
      { name: "Playing cards", essential: false },
      { name: "Glow sticks", essential: false },
      { name: "Inflatable (check size rules)", essential: false },
    ],
  },
]

export const quizQuestions = [
  {
    id: 1,
    question: "What's your ideal festival vibe?",
    options: [
      { text: "Non-stop dancing and bass drops", tags: ["electronic", "rave", "energetic"] },
      { text: "Headbanging and mosh pits", tags: ["rock", "metal", "intense"] },
      { text: "Chilled vibes and artistic discovery", tags: ["indie", "artsy", "relaxed"] },
      { text: "Family fun with something for everyone", tags: ["family", "diverse", "accessible"] },
    ],
  },
  {
    id: 2,
    question: "How do you feel about camping?",
    options: [
      { text: "Love it! Part of the experience", tags: ["camping", "full-experience"] },
      { text: "Prefer glamping or comfort", tags: ["glamping", "comfort"] },
      { text: "Rather sleep in my own bed", tags: ["day-festival", "city"] },
      { text: "Whatever gets me to the music!", tags: ["flexible"] },
    ],
  },
  {
    id: 3,
    question: "What's your budget like?",
    options: [
      { text: "Money's no object for a great time", tags: ["premium", "big-budget"] },
      { text: "Happy to spend for quality", tags: ["mid-budget"] },
      { text: "Looking for value", tags: ["budget", "affordable"] },
      { text: "Free entry would be nice!", tags: ["free", "budget"] },
    ],
  },
  {
    id: 4,
    question: "Who are you going with?",
    options: [
      { text: "Big group of mates", tags: ["social", "party"] },
      { text: "Just me or a partner", tags: ["intimate", "couple"] },
      { text: "The whole family", tags: ["family", "kids"] },
      { text: "Making new friends there!", tags: ["social", "community"] },
    ],
  },
  {
    id: 5,
    question: "Pick your favourite genre:",
    options: [
      { text: "Electronic/Dance/House", tags: ["electronic", "house", "techno"] },
      { text: "Rock/Metal/Punk", tags: ["rock", "metal", "punk"] },
      { text: "Indie/Alternative/Folk", tags: ["indie", "alternative", "folk"] },
      { text: "Hip-Hop/R&B/Grime", tags: ["hip-hop", "rnb", "urban"] },
    ],
  },
]

export const travelTips = [
  {
    title: "By Car",
    icon: "car",
    tips: [
      "Book parking in advance - it sells out!",
      "Leave very early to avoid traffic jams",
      "Pack a printed map - signals can be patchy",
      "Bring snacks for potential long queues",
      "Know your designated drop-off zone",
    ],
  },
  {
    title: "By Train",
    icon: "train",
    tips: [
      "Book advance tickets for best prices",
      "Check for special festival shuttle buses",
      "Travel light - you'll carry everything",
      "Consider arriving a day early",
      "Save offline train times in case of no signal",
    ],
  },
  {
    title: "By Coach",
    icon: "bus",
    tips: [
      "Official festival coaches often include entry",
      "Pick-ups from major cities available",
      "Usually drops you right at the entrance",
      "Pre-book to secure your seat",
      "Great for groups!",
    ],
  },
]

export const accommodationTypes = [
  {
    name: "Standard Camping",
    price: "Included",
    description: "Bring your own tent and gear. The classic festival experience.",
    pros: ["Cheapest option", "Authentic experience", "Social atmosphere"],
    cons: ["Can be uncomfortable", "Weather dependent", "Far from stages"],
  },
  {
    name: "Pre-Pitched Tent",
    price: "£150-300",
    description: "Tent already set up when you arrive. Just bring your sleeping bag.",
    pros: ["Less to carry", "Good location usually", "Time saver"],
    cons: ["Limited customisation", "Extra cost", "May need own bedding"],
  },
  {
    name: "Glamping",
    price: "£400-1500",
    description: "Luxury camping with proper beds, furniture, and sometimes ensuite.",
    pros: ["Comfortable beds", "Private space", "Often near facilities"],
    cons: ["Expensive", "Books up fast", "Less spontaneous"],
  },
  {
    name: "Campervan",
    price: "£100-200 pass",
    description: "Bring your home on wheels. Need campervan ticket.",
    pros: ["Your own space", "Cooking facilities", "Lock up valuables"],
    cons: ["Need a van", "Designated areas only", "Limited spaces"],
  },
  {
    name: "Off-Site",
    price: "£50-200/night",
    description: "Hotels, B&Bs, or Airbnbs near the festival.",
    pros: ["Real bed", "Hot showers", "Quiet sleep"],
    cons: ["Daily commute", "Miss late night vibes", "Can be far"],
  },
]

export const weatherAdvice = [
  {
    condition: "Sun",
    icon: "sun",
    tips: [
      "Wear SPF 30+ sunscreen",
      "Stay hydrated - drink lots of water",
      "Find shade during hottest hours",
      "Wear a hat",
      "Light, breathable clothing",
    ],
  },
  {
    condition: "Rain",
    icon: "cloud-rain",
    tips: [
      "Wellies are essential!",
      "Waterproof jacket (not just water resistant)",
      "Dry bags for electronics",
      "Extra socks in plastic bag",
      "Embrace the mud!",
    ],
  },
  {
    condition: "Wind",
    icon: "wind",
    tips: [
      "Secure your tent with extra guy ropes",
      "Pack layers that layer well",
      "Bring a windbreaker",
      "Avoid tall inflatables",
      "Know where solid structures are",
    ],
  },
  {
    condition: "Cold Nights",
    icon: "thermometer",
    tips: [
      "Bring a warm sleeping bag",
      "Pack thermals/base layers",
      "Wear a hat to bed",
      "Hot water bottle",
      "Check minimum temps for your dates",
    ],
  },
]

export const festivalAdvice = [
  {
    category: "First Timers",
    tips: [
      "Arrive early to get a good camping spot",
      "Take a photo of where you're camped (it all looks the same at 3am!)",
      "Pace yourself - it's a marathon not a sprint",
      "Wear your wellies in, even if it's sunny",
      "Make a rough schedule but stay flexible",
      "Designate a meeting spot if you lose your group",
    ],
  },
  {
    category: "Staying Safe",
    tips: [
      "Know where the medical tent is",
      "Stay hydrated - water is more important than you think",
      "Look after your mates",
      "Trust your instincts",
      "Keep valuables secure or leave them at home",
      "Know your limits with alcohol",
    ],
  },
  {
    category: "Money Saving",
    tips: [
      "Bring your own food for breakfasts",
      "Refillable water bottles save a fortune",
      "Early bird tickets are always cheaper",
      "Check payment options - some are cashless",
      "Volunteer for free entry (apply early!)",
      "Share transport costs with mates",
    ],
  },
  {
    category: "Pro Tips",
    tips: [
      "Freeze bottles of water - keeps cool box cold AND melts into drinking water",
      "Bring a small bag/bumbag for the arena",
      "Dry shampoo and wet wipes are game changers",
      "Portable phone charger is essential",
      "Download the festival app for schedules",
      "Check the line-up before you go - plan must-sees",
    ],
  },
]
